export const NLLB_LANGUAGES = [
  { code: "ace_Arab", name: "Acehnese", variant: "Arabic script" },
  { code: "ace_Latn", name: "Acehnese", variant: "Latin" },
  { code: "acm_Arab", name: "Arabic", variant: "Mesopotamian" },
  { code: "acq_Arab", name: "Arabic", variant: "Yemeni" },
  { code: "aeb_Arab", name: "Arabic", variant: "Tunisian" },
  { code: "afr_Latn", name: "Afrikaans", variant: "Latin" },
  { code: "ajp_Arab", name: "Arabic", variant: "South Levantine" },
  { code: "aka_Latn", name: "Akan", variant: "Latin" },
  { code: "apc_Arab", name: "Arabic", variant: "Levantine" },
  { code: "arb_Arab", name: "Arabic", variant: "Modern Standard" },
  { code: "ars_Arab", name: "Arabic", variant: "Najdi" },
  { code: "ary_Arab", name: "Arabic", variant: "Moroccan" },
  { code: "arz_Arab", name: "Arabic", variant: "Egyptian" },
  { code: "asm_Beng", name: "Assamese", variant: "Bengali" },
  { code: "ast_Latn", name: "Asturian", variant: "Latin" },
  { code: "awa_Deva", name: "Awadhi", variant: "Devanagari" },
  { code: "ayr_Latn", name: "Aymara", variant: "Latin" },
  { code: "azb_Arab", name: "Azerbaijani", variant: "Arabic script" },
  { code: "azj_Latn", name: "Azerbaijani", variant: "Latin" },
  { code: "bak_Cyrl", name: "Bashkir", variant: "Cyrillic" },
  { code: "bam_Latn", name: "Bambara", variant: "Latin" },
  { code: "ban_Latn", name: "Balinese", variant: "Latin" },
  { code: "bel_Cyrl", name: "Belarusian", variant: "Cyrillic" },
  { code: "bem_Latn", name: "Bemba", variant: "Latin" },
  { code: "ben_Beng", name: "Bengali", variant: "Bengali" },
  { code: "bho_Deva", name: "Bhojpuri", variant: "Devanagari" },
  { code: "bjn_Arab", name: "Banjar", variant: "Arabic script" },
  { code: "bjn_Latn", name: "Banjar", variant: "Latin" },
  { code: "bos_Latn", name: "Bosnian", variant: "Latin" },
  { code: "bug_Latn", name: "Buginese", variant: "Latin" },
  { code: "bul_Cyrl", name: "Bulgarian", variant: "Cyrillic" },
  { code: "cat_Latn", name: "Catalan", variant: "Latin" },
  { code: "ceb_Latn", name: "Cebuano", variant: "Latin" },
  { code: "ces_Latn", name: "Czech", variant: "Latin" },
  { code: "cjk_Latn", name: "Chokwe", variant: "Latin" },
  { code: "ckb_Arab", name: "Kurdish (Sorani)", variant: "Arabic script" },
  { code: "crh_Latn", name: "Crimean Tatar", variant: "Latin" },
  { code: "cym_Latn", name: "Welsh", variant: "Latin" },
  { code: "dan_Latn", name: "Danish", variant: "Latin" },
  { code: "deu_Latn", name: "German", variant: "Latin" },
  { code: "dik_Latn", name: "Dinka", variant: "Latin" },
  { code: "dyu_Latn", name: "Dyula", variant: "Latin" },
  { code: "eng_Latn", name: "English", variant: "Latin" },
  { code: "epo_Latn", name: "Esperanto", variant: "Latin" },
  { code: "est_Latn", name: "Estonian", variant: "Latin" },
  { code: "eus_Latn", name: "Basque", variant: "Latin" },
  { code: "ewe_Latn", name: "Ewe", variant: "Latin" },
  { code: "fao_Latn", name: "Faroese", variant: "Latin" },
  { code: "pes_Arab", name: "Persian", variant: "Arabic script" },
  { code: "fij_Latn", name: "Fijian", variant: "Latin" },
  { code: "fin_Latn", name: "Finnish", variant: "Latin" },
  { code: "fon_Latn", name: "Fon", variant: "Latin" },
  { code: "fra_Latn", name: "French", variant: "Latin" },
  { code: "fur_Latn", name: "Friulian", variant: "Latin" },
  { code: "fuv_Latn", name: "Fulfulde", variant: "Latin" },
  { code: "gla_Latn", name: "Scottish Gaelic", variant: "Latin" },
  { code: "gle_Latn", name: "Irish", variant: "Latin" },
  { code: "glg_Latn", name: "Galician", variant: "Latin" },
  { code: "grn_Latn", name: "Guarani", variant: "Latin" },
  { code: "hat_Latn", name: "Haitian Creole", variant: "Latin" },
  { code: "hau_Latn", name: "Hausa", variant: "Latin" },
  { code: "hin_Deva", name: "Hindi", variant: "Devanagari" },
  { code: "hne_Deva", name: "Chhattisgarhi", variant: "Devanagari" },
  { code: "hrv_Latn", name: "Croatian", variant: "Latin" },
  { code: "hun_Latn", name: "Hungarian", variant: "Latin" },
  { code: "ibo_Latn", name: "Igbo", variant: "Latin" },
  { code: "ilo_Latn", name: "Ilocano", variant: "Latin" },
  { code: "ind_Latn", name: "Indonesian", variant: "Latin" },
  { code: "isl_Latn", name: "Icelandic", variant: "Latin" },
  { code: "ita_Latn", name: "Italian", variant: "Latin" },
  { code: "jav_Latn", name: "Javanese", variant: "Latin" },
  { code: "kab_Latn", name: "Kabyle", variant: "Latin" },
  { code: "kac_Latn", name: "Kachin", variant: "Latin" },
  { code: "kam_Latn", name: "Kamba", variant: "Latin" },
  { code: "kas_Arab", name: "Kashmiri", variant: "Arabic script" },
  { code: "kas_Deva", name: "Kashmiri", variant: "Devanagari" },
  { code: "knc_Arab", name: "Kanuri", variant: "Arabic script" },
  { code: "knc_Latn", name: "Kanuri", variant: "Latin" },
  { code: "kaz_Cyrl", name: "Kazakh", variant: "Cyrillic" },
  { code: "kbp_Latn", name: "Kabiyè", variant: "Latin" },
  { code: "kea_Latn", name: "Kabuverdianu", variant: "Latin" },
  { code: "kik_Latn", name: "Kikuyu", variant: "Latin" },
  { code: "kin_Latn", name: "Kinyarwanda", variant: "Latin" },
  { code: "kir_Cyrl", name: "Kyrgyz", variant: "Cyrillic" },
  { code: "kmb_Latn", name: "Kimbundu", variant: "Latin" },
  { code: "kon_Latn", name: "Kongo", variant: "Latin" },
  { code: "kmr_Latn", name: "Kurdish (Kurmanji)", variant: "Latin" },
  { code: "lvs_Latn", name: "Latvian", variant: "Latin" },
  { code: "lij_Latn", name: "Ligurian", variant: "Latin" },
  { code: "lim_Latn", name: "Limburgish", variant: "Latin" },
  { code: "lin_Latn", name: "Lingala", variant: "Latin" },
  { code: "lit_Latn", name: "Lithuanian", variant: "Latin" },
  { code: "lmo_Latn", name: "Lombard", variant: "Latin" },
  { code: "ltg_Latn", name: "Latgalian", variant: "Latin" },
  { code: "ltz_Latn", name: "Luxembourgish", variant: "Latin" },
  { code: "lua_Latn", name: "Luba-Kasai", variant: "Latin" },
  { code: "lug_Latn", name: "Luganda", variant: "Latin" },
  { code: "luo_Latn", name: "Luo", variant: "Latin" },
  { code: "lus_Latn", name: "Mizo", variant: "Latin" },
  { code: "mag_Deva", name: "Magahi", variant: "Devanagari" },
  { code: "mai_Deva", name: "Maithili", variant: "Devanagari" },
  { code: "mar_Deva", name: "Marathi", variant: "Devanagari" },
  { code: "min_Latn", name: "Minangkabau", variant: "Latin" },
  { code: "mkd_Cyrl", name: "Macedonian", variant: "Cyrillic" },
  { code: "plt_Latn", name: "Malagasy", variant: "Latin" },
  { code: "mlt_Latn", name: "Maltese", variant: "Latin" },
  { code: "mni_Beng", name: "Manipuri", variant: "Bengali" },
  { code: "khk_Cyrl", name: "Mongolian", variant: "Cyrillic" },
  { code: "mos_Latn", name: "Mossi", variant: "Latin" },
  { code: "mri_Latn", name: "Maori", variant: "Latin" },
  { code: "zsm_Latn", name: "Malay", variant: "Latin" },
  { code: "nld_Latn", name: "Dutch", variant: "Latin" },
  { code: "nno_Latn", name: "Norwegian Nynorsk", variant: "Latin" },
  { code: "nob_Latn", name: "Norwegian Bokmål", variant: "Latin" },
  { code: "npi_Deva", name: "Nepali", variant: "Devanagari" },
  { code: "nso_Latn", name: "Northern Sotho", variant: "Latin" },
  { code: "nus_Latn", name: "Nuer", variant: "Latin" },
  { code: "nya_Latn", name: "Nyanja", variant: "Latin" },
  { code: "oci_Latn", name: "Occitan", variant: "Latin" },
  { code: "gaz_Latn", name: "Oromo", variant: "Latin" },
  { code: "pag_Latn", name: "Pangasinan", variant: "Latin" },
  { code: "pap_Latn", name: "Papiamento", variant: "Latin" },
  { code: "pol_Latn", name: "Polish", variant: "Latin" },
  { code: "por_Latn", name: "Portuguese", variant: "Latin" },
  { code: "prs_Arab", name: "Dari", variant: "Arabic script" },
  { code: "pbt_Arab", name: "Pashto", variant: "Arabic script" },
  { code: "quy_Latn", name: "Quechua", variant: "Latin" },
  { code: "ron_Latn", name: "Romanian", variant: "Latin" },
  { code: "run_Latn", name: "Kirundi", variant: "Latin" },
  { code: "rus_Cyrl", name: "Russian", variant: "Cyrillic" },
  { code: "sag_Latn", name: "Sango", variant: "Latin" },
  { code: "san_Deva", name: "Sanskrit", variant: "Devanagari" },
  { code: "sat_Beng", name: "Santali", variant: "Bengali" },
  { code: "scn_Latn", name: "Sicilian", variant: "Latin" },
  { code: "slk_Latn", name: "Slovak", variant: "Latin" },
  { code: "slv_Latn", name: "Slovenian", variant: "Latin" },
  { code: "smo_Latn", name: "Samoan", variant: "Latin" },
  { code: "sna_Latn", name: "Shona", variant: "Latin" },
  { code: "snd_Arab", name: "Sindhi", variant: "Arabic script" },
  { code: "som_Latn", name: "Somali", variant: "Latin" },
  { code: "sot_Latn", name: "Southern Sotho", variant: "Latin" },
  { code: "spa_Latn", name: "Spanish", variant: "Latin" },
  { code: "als_Latn", name: "Albanian", variant: "Latin" },
  { code: "srd_Latn", name: "Sardinian", variant: "Latin" },
  { code: "srp_Cyrl", name: "Serbian", variant: "Cyrillic" },
  { code: "ssw_Latn", name: "Swati", variant: "Latin" },
  { code: "sun_Latn", name: "Sundanese", variant: "Latin" },
  { code: "swe_Latn", name: "Swedish", variant: "Latin" },
  { code: "swh_Latn", name: "Swahili", variant: "Latin" },
  { code: "szl_Latn", name: "Silesian", variant: "Latin" },
  { code: "tat_Cyrl", name: "Tatar", variant: "Cyrillic" },
  { code: "tgk_Cyrl", name: "Tajik", variant: "Cyrillic" },
  { code: "tgl_Latn", name: "Tagalog", variant: "Latin" },
  { code: "tha_Thai", name: "Thai", variant: "Thai" },
  { code: "taq_Latn", name: "Tamasheq", variant: "Latin" },
  { code: "tpi_Latn", name: "Tok Pisin", variant: "Latin" },
  { code: "tsn_Latn", name: "Tswana", variant: "Latin" },
  { code: "tso_Latn", name: "Tsonga", variant: "Latin" },
  { code: "tuk_Latn", name: "Turkmen", variant: "Latin" },
  { code: "tum_Latn", name: "Tumbuka", variant: "Latin" },
  { code: "tur_Latn", name: "Turkish", variant: "Latin" },
  { code: "twi_Latn", name: "Twi", variant: "Latin" },
  { code: "uig_Arab", name: "Uyghur", variant: "Arabic script" },
  { code: "ukr_Cyrl", name: "Ukrainian", variant: "Cyrillic" },
  { code: "umb_Latn", name: "Umbundu", variant: "Latin" },
  { code: "urd_Arab", name: "Urdu", variant: "Arabic script" },
  { code: "uzn_Latn", name: "Uzbek", variant: "Latin" },
  { code: "vec_Latn", name: "Venetian", variant: "Latin" },
  { code: "vie_Latn", name: "Vietnamese", variant: "Latin" },
  { code: "war_Latn", name: "Waray", variant: "Latin" },
  { code: "wol_Latn", name: "Wolof", variant: "Latin" },
  { code: "xho_Latn", name: "Xhosa", variant: "Latin" },
  { code: "yor_Latn", name: "Yoruba", variant: "Latin" },
  { code: "zul_Latn", name: "Zulu", variant: "Latin" },
  { code: "amh_Ethi", name: "Amharic", variant: "Ethiopic" },
  { code: "bod_Tibt", name: "Tibetan", variant: "Tibetan" },
  { code: "dzo_Tibt", name: "Dzongkha", variant: "Tibetan" },
  { code: "ell_Grek", name: "Greek", variant: "Greek" },
  { code: "guj_Gujr", name: "Gujarati", variant: "Gujarati" },
  { code: "heb_Hebr", name: "Hebrew", variant: "Hebrew" },
  { code: "hye_Armn", name: "Armenian", variant: "Armenian" },
  { code: "jpn_Jpan", name: "Japanese", variant: "Japanese" },
  { code: "kan_Knda", name: "Kannada", variant: "Kannada" },
  { code: "kat_Geor", name: "Georgian", variant: "Georgian" },
  { code: "khm_Khmr", name: "Khmer", variant: "Khmer" },
  { code: "kor_Hang", name: "Korean", variant: "Hangul" },
  { code: "lao_Laoo", name: "Lao", variant: "Lao" },
  { code: "mal_Mlym", name: "Malayalam", variant: "Malayalam" },
  { code: "mya_Mymr", name: "Burmese", variant: "Myanmar" },
  { code: "ory_Orya", name: "Odia", variant: "Odia" },
  { code: "pan_Guru", name: "Punjabi", variant: "Gurmukhi" },
  { code: "shn_Mymr", name: "Shan", variant: "Myanmar" },
  { code: "sin_Sinh", name: "Sinhala", variant: "Sinhala" },
  { code: "tam_Taml", name: "Tamil", variant: "Tamil" },
  { code: "tel_Telu", name: "Telugu", variant: "Telugu" },
  { code: "tir_Ethi", name: "Tigrinya", variant: "Ethiopic" },
  { code: "taq_Tfng", name: "Tamasheq", variant: "Tifinagh" },
  { code: "tzm_Tfng", name: "Central Atlas Tamazight", variant: "Tifinagh" },
  { code: "ydd_Hebr", name: "Yiddish", variant: "Hebrew" },
  { code: "yue_Hant", name: "Cantonese", variant: "Traditional" },
  { code: "zho_Hans", name: "Chinese Simplified", variant: "Simplified" },
  { code: "zho_Hant", name: "Chinese Traditional", variant: "Traditional" }
];
